import { Inter } from "next/font/google";
import "./globals.css";
import AutoFixHighIcon from "@mui/icons-material/AutoFixHigh";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AutoCapGen Pro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + 
      "bg-gradient-to-bl from-rose-400 via-fuchsia-500 to-indigo-500"}>
      <main className="bg-gradient-to-bl from-rose-400 via-fuchsia-500 to-indigo-500 
      min-h-screen text-white overflow-hidden">
      <Header/>
      {children}
      <Footer/>
      </main>     
      </body>
    </html>
  );
}
